python cflp.py mess cap/PublicInstances/toy.dzn

python cflp.py mess cap/PublicInstances/wlp01.dzn
python cflp.py mess cap/PublicInstances/wlp02.dzn
python cflp.py mess cap/PublicInstances/wlp03.dzn
python cflp.py mess cap/PublicInstances/wlp04.dzn
python cflp.py mess cap/PublicInstances/wlp05.dzn
python cflp.py mess cap/PublicInstances/wlp06.dzn
python cflp.py mess cap/PublicInstances/wlp07.dzn
python cflp.py mess cap/PublicInstances/wlp08.dzn
python cflp.py mess cap/PublicInstances/wlp09.dzn
python cflp.py mess cap/PublicInstances/wlp10.dzn
python cflp.py mess cap/PublicInstances/wlp11.dzn
python cflp.py mess cap/PublicInstances/wlp12.dzn
python cflp.py mess cap/PublicInstances/wlp13.dzn
python cflp.py mess cap/PublicInstances/wlp14.dzn
python cflp.py mess cap/PublicInstances/wlp15.dzn
python cflp.py mess cap/PublicInstances/wlp16.dzn
python cflp.py mess cap/PublicInstances/wlp17.dzn
python cflp.py mess cap/PublicInstances/wlp18.dzn
python cflp.py mess cap/PublicInstances/wlp19.dzn
python cflp.py mess cap/PublicInstances/wlp20.dzn
